### ISSUE TITLE
Nutzen von entsprechenden Umgebungen für Sätze, Lemmata und Korollare

### ISSUE THREAD

**Issue by jhackenberg** [hpi-mitschriften/mathe-vorkurs#9]
Für Sätze, Lemmata und Korollare sollte jeweils eine entsprechende Umgebung genutzt werden.
https://www.overleaf.com/learn/latex/Theorems_and_proofs

**Comment by YoanWithY** [comment]
Die Vorlesung selbst hält diese Struktur nicht konsequent genug durch, als dass es realistisch (oder notwendig) wäre, diese Umgebungen  zu nutzen. Ich denke nicht, dass der Nutzen in diesem Fall den Aufwand rechtfertigen würde.
